# Generated by Django 4.2.6 on 2023-10-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
